steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/testgocloudmysql:65060af9d122bda9d4a005b2e80f22efbdd0346257fa708deaabaf51fd8d870e', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'testgocloudmysql',
           '--image', 'gcr.io/$PROJECT_ID/testgocloudmysql:65060af9d122bda9d4a005b2e80f22efbdd0346257fa708deaabaf51fd8d870e',
           '--set-env-vars', 'MYSQL_HOST=mysql-container',
           '--set-env-vars', 'MYSQL_PORT=3306',
           '--set-env-vars', 'MYSQL_DATABASE=test',
           '--set-env-vars', 'MYSQL_USER=root',
           '--set-env-vars', 'MYSQL_PASSWORD=password',
           '--region', 'asia-northeast1',
           '--service-account', 'cloudbuild@arcane-woods-416203.iam.gserviceaccount.com']

images:
  - 'gcr.io/$PROJECT_ID/testgocloudmysql:65060af9d122bda9d4a005b2e80f22efbdd0346257fa708deaabaf51fd8d870e'
